### PR TITLE
Update app template to 0.0.2

### PR DESCRIPTION
**Pull request by wasnotrice**
This is an update to #17, including @tlemburg's changes there, and also incorporating @jasonrclark's new app template. Closes #17

### CODE REVIEW

**Comment by jasonrclark** [comment]
Ran this locally, got the new template and it ran cleanly for me. :+1:

**Comment by tlemburg** [comment]
I also ran it, looks like we're all set :)

**Comment by jasonrclark** [comment]
:metal:

**Comment by PragTob** [comment]
Then I'll go ahead and do the honors, thanks everyone!!! :)

**Pull request merged**
