### PR TITLE
Update base JRuby version to 9.1.8.0

### PR DESCRIPTION
**Pull request by jasonrclark**
Just like it says on the tin

### CODE REVIEW

**Comment by PragTob** [comment]
The tin forgot to adjust the travis.yml - afterwards good to go :)

**Comment by PragTob** [comment]
CI seems to fail consistently on openJDK 7 with some SSL errors or whatever :|

Looks like a regression on the JRuby side though...

```
1) Furoshiki::JarApp when creating a .app creates a .app

     Failure/Error: Net::HTTP.start(uri.host, uri.port, :use_ssl => uri.scheme == 'https') do |http|

     

     OpenSSL::SSL::SSLError:

       Unsupported record version Unknown-0.0

     # ./lib/furoshiki/jar_app.rb:111:in `download_following_redirects'

     # ./lib/furoshiki/jar_app.rb:101:in `download'

     # ./lib/furoshiki/jar_app.rb:97:in `download_template'

     # ./lib/furoshiki/jar_app.rb:77:in `cache_template'

     # ./lib/furoshiki/jar_app.rb:52:in `package'

     # ./spec/app_spec.rb:62:in `block in (root)'

     # ./spec/app_spec.rb:59:in `block in (root)'

  2) Furoshiki::JarApp when creating a .app includes launcher

     Failure/Error: Net::HTTP.start(uri.host, uri.port, :use_ssl => uri.scheme == 'https') do |http|

     

     OpenSSL::SSL::SSLError:

       Unsupported record version Unknown-0.0

     # ./lib/furoshiki/jar_app.rb:111:in `download_following_redirects'

     # ./lib/furoshiki/jar_app.rb:101:in `download'

     # ./lib/furoshiki/jar_app.rb:97:in `download_template'

     # ./lib/furoshiki/jar_app.rb:77:in `cache_template'

     # ./lib/furoshiki/jar_app.rb:52:in `package'

     # ./spec/app_spec.rb:62:in `block in (root)'

     # ./spec/app_spec.rb:59:in `block in (root)'

  3) Furoshiki::JarApp when creating a .app makes launcher executable

     Failure/Error: Net::HTTP.start(uri.host, uri.port, :use_ssl => uri.scheme == 'https') do |http|

     

     OpenSSL::SSL::SSLError:

       Unsupported record version Unknown-0.0

     # ./lib/furoshiki/jar_app.rb:111:in `download_following_redirects'

     # ./lib/furoshiki/jar_app.rb:101:in `download'

     # ./lib/furoshiki/jar_app.rb:97:in `download_template'

     # ./lib/furoshiki/jar_app.rb:77:in `cache_template'

     # ./lib/furoshiki/jar_app.rb:52:in `package'

     # ./spec/app_spec.rb:62:in `block in (root)'

     # ./spec/app_spec.rb:59:in `block in (root)'

  4) Furoshiki::JarApp when creating a .app deletes generic icon

     Failure/Error: Net::HTTP.start(uri.host, uri.port, :use_ssl => uri.scheme == 'https') do |http|

     

     OpenSSL::SSL::SSLError:

       Unsupported record version Unknown-0.0

     # ./lib/furoshiki/jar_app.rb:111:in `download_following_redirects'

     # ./lib/furoshiki/jar_app.rb:101:in `download'

     # ./lib/furoshiki/jar_app.rb:97:in `download_template'

     # ./lib/furoshiki/jar_app.rb:77:in `cache_template'

     # ./lib/furoshiki/jar_app.rb:52:in `package'

     # ./spec/app_spec.rb:62:in `block in (root)'

     # ./spec/app_spec.rb:59:in `block in (root)'

  5) Furoshiki::JarApp when creating a .app injects icon

     Failure/Error: Net::HTTP.start(uri.host, uri.port, :use_ssl => uri.scheme == 'https') do |http|

     

     OpenSSL::SSL::SSLError:

       Unsupported record version Unknown-0.0

     # ./lib/furoshiki/jar_app.rb:111:in `download_following_redirects'

     # ./lib/furoshiki/jar_app.rb:101:in `download'

     # ./lib/furoshiki/jar_app.rb:97:in `download_template'

     # ./lib/furoshiki/jar_app.rb:77:in `cache_template'

     # ./lib/furoshiki/jar_app.rb:52:in `package'

     # ./spec/app_spec.rb:62:in `block in (root)'

     # ./spec/app_spec.rb:59:in `block in (root)'

  6) Furoshiki::JarApp when creating a .app injects jar

     Failure/Error: Net::HTTP.start(uri.host, uri.port, :use_ssl => uri.scheme == 'https') do |http|

     

     OpenSSL::SSL::SSLError:

       Unsupported record version Unknown-0.0

     # ./lib/furoshiki/jar_app.rb:111:in `download_following_redirects'

     # ./lib/furoshiki/jar_app.rb:101:in `download'

     # ./lib/furoshiki/jar_app.rb:97:in `download_template'

     # ./lib/furoshiki/jar_app.rb:77:in `cache_template'

     # ./lib/furoshiki/jar_app.rb:52:in `package'

     # ./spec/app_spec.rb:62:in `block in (root)'

     # ./spec/app_spec.rb:59:in `block in (root)'

  7) Furoshiki::JarApp when creating a .app removes any extraneous jars

     Failure/Error: Net::HTTP.start(uri.host, uri.port, :use_ssl => uri.scheme == 'https') do |http|

     

     OpenSSL::SSL::SSLError:

       Unsupported record version Unknown-0.0

     # ./lib/furoshiki/jar_app.rb:111:in `download_following_redirects'

     # ./lib/furoshiki/jar_app.rb:101:in `download'

     # ./lib/furoshiki/jar_app.rb:97:in `download_template'

     # ./lib/furoshiki/jar_app.rb:77:in `cache_template'

     # ./lib/furoshiki/jar_app.rb:52:in `package'

     # ./spec/app_spec.rb:62:in `block in (root)'

     # ./spec/app_spec.rb:59:in `block in (root)'

  8) Furoshiki::JarApp when creating a .app template_path 

     Failure/Error: Net::HTTP.start(uri.host, uri.port, :use_ssl => uri.scheme == 'https') do |http|

     

     OpenSSL::SSL::SSLError:

       Unsupported record version Unknown-0.0

     # ./lib/furoshiki/jar_app.rb:111:in `download_following_redirects'

     # ./lib/furoshiki/jar_app.rb:101:in `download'

     # ./lib/furoshiki/jar_app.rb:97:in `download_template'

     # ./lib/furoshiki/jar_app.rb:77:in `cache_template'

     # ./lib/furoshiki/jar_app.rb:52:in `package'

     # ./spec/app_spec.rb:62:in `block in (root)'

     # ./spec/app_spec.rb:59:in `block in (root)'

  9) Furoshiki::JarApp when creating a .app Info.plist sets identifier

     Failure/Error: Net::HTTP.start(uri.host, uri.port, :use_ssl => uri.scheme == 'https') do |http|

     

     OpenSSL::SSL::SSLError:

       Unsupported record version Unknown-0.0

     # ./lib/furoshiki/jar_app.rb:111:in `download_following_redirects'

     # ./lib/furoshiki/jar_app.rb:101:in `download'

     # ./lib/furoshiki/jar_app.rb:97:in `download_template'

     # ./lib/furoshiki/jar_app.rb:77:in `cache_template'

     # ./lib/furoshiki/jar_app.rb:52:in `package'

     # ./spec/app_spec.rb:62:in `block in (root)'

     # ./spec/app_spec.rb:59:in `block in (root)'

  10) Furoshiki::JarApp when creating a .app Info.plist sets display name

      Failure/Error: Net::HTTP.start(uri.host, uri.port, :use_ssl => uri.scheme == 'https') do |http|

      

      OpenSSL::SSL::SSLError:

        Unsupported record version Unknown-0.0

      # ./lib/furoshiki/jar_app.rb:111:in `download_following_redirects'

      # ./lib/furoshiki/jar_app.rb:101:in `download'

      # ./lib/furoshiki/jar_app.rb:97:in `download_template'[0m

      # ./lib/furoshiki/jar_app.rb:77:in `cache_template'

      # ./lib/furoshiki/jar_app.rb:52:in `package'

      # ./spec/app_spec.rb:62:in `block in (root)'

      # ./spec/app_spec.rb:59:in `block in (root)'

  11) Furoshiki::JarApp when creating a .app Info.plist sets bundle name

      Failure/Error: Net::HTTP.start(uri.host, uri.port, :use_ssl => uri.scheme == 'https') do |http|

      

      OpenSSL::SSL::SSLError:

        Unsupported record version Unknown-0.0

      # ./lib/furoshiki/jar_app.rb:111:in `download_following_redirects'

      # ./lib/furoshiki/jar_app.rb:101:in `download'

      # ./lib/furoshiki/jar_app.rb:97:in `download_template'

      # ./lib/furoshiki/jar_app.rb:77:in `cache_template'

      # ./lib/furoshiki/jar_app.rb:52:in `package'

      # ./spec/app_spec.rb:62:in `block in (root)'

      # ./spec/app_spec.rb:59:in `block in (root)'

  12) Furoshiki::JarApp when creating a .app Info.plist sets icon

      Failure/Error: Net::HTTP.start(uri.host, uri.port, :use_ssl => uri.scheme == 'https') do |http|

      

      OpenSSL::SSL::SSLError:

        Unsupported record version Unknown-0.0

      # ./lib/furoshiki/jar_app.rb:111:in `download_following_redirects'

      # ./lib/furoshiki/jar_app.rb:101:in `download'

      36m# ./lib/furoshiki/jar_app.rb:97:in `download_template'

      # ./lib/furoshiki/jar_app.rb:77:in `cache_template'

      # ./lib/furoshiki/jar_app.rb:52:in `package'

      # ./spec/app_spec.rb:62:in `block in (root)'

      # ./spec/app_spec.rb:59:in `block in (root)'

  13) Furoshiki::JarApp when creating a .app Info.plist sets version

      Failure/Error: Net::HTTP.start(uri.host, uri.port, :use_ssl => uri.scheme == 'https') do |http|

      

      OpenSSL::SSL::SSLError:

        Unsupported record version Unknown-0.0

      # ./lib/furoshiki/jar_app.rb:111:in `download_following_redirects'

      # ./lib/furoshiki/jar_app.rb:101:in `download'

      # ./lib/furoshiki/jar_app.rb:97:in `download_template'

      # ./lib/furoshiki/jar_app.rb:77:in `cache_template'

      # ./lib/furoshiki/jar_app.rb:52:in `package'

      # ./spec/app_spec.rb:62:in `block in (root)'

      # ./spec/app_spec.rb:59:in `block in (root)'

Finished in 27.32 seconds (files took 1.33 seconds to load)

48 examples, 13 failures
```

**Comment by PragTob** [comment]
Ok tried switching us over to JDK 8 in hopes that it's just a JDK7 oddity and we can just up requirements and not deal with it.

**Comment by PragTob** [comment]
Well, what do you say - is just running on JDK8 good enough (tm) ?

**Comment by jasonrclark** [comment]
Busy weekend and didn't get 👟  time!

JDK8 is totally "Good Enough"! :shipit:

**Comment by PragTob** [comment]
No worries, was just looking at stuff and if we wanted to implement this over in the main repo as well and was wondering whether you had any objections :)

**Pull request merged**
